version: '3.8'
services:

  kitchen-db:
    image: postgres:15.1-alpine
    container_name: financial-organisation-service
    environment:
      - POSTGRES_DB=financial-organisation-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

